parameters:
#    client_feedback.example.class: Client\FeedbackBundle\Example

services:
#    client_feedback.example:
#        class: %client_feedback.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
